version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=db
      - OPENAPI_API_KEY=${OPENAPI_API_KEY}

  postgres:
    image: postgres:14-alpine
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=db


